# 목표

* 로컬 개발 환경
** 소스와 빌드 산출물 분리
** watch기능으로 변경을 지속적 반영
* 운영 배포 가능 (Minified, ES2016 Babel compile, SCSS compile 등등)




## Persistent Layer

### JPA Framework

주요 영속성 메커니즘으로 JPA(Eclipselink)를 사용한다.  hibernate가 더 대중적으로 사용되지만, eclipselink가 제공하는 강력한 lazy loading(session이 끊긴상태에서 객체 그래프 조회시 자동으로 세션을 열어 필요한 데이터를 가져올수 있다)과 batch fetch  때문 선정하였다.


### QueryDSL
기본적인 영속성 구조는 Spring Data를 이용한다. 여기에 복잡한 조회를 위해  querydsl을 이용한다.
QueryDSL은 JPA Entity 클래스에 대해 query tytpe 클래스 생성이 필요하다.
QueryDSL query type 은 src/main/generated 폴더 밑에 생성된다.

----
task generateQueryDSL(type: JavaCompile, group: 'build', description: 'Generates the QueryDSL query types') {
    source = sourceSets.main.java
    classpath = configurations.compile + configurations.querydslapt
    options.compilerArgs = [
            "-proc:only",
            "-processor", "com.mysema.query.apt.jpa.JPAAnnotationProcessor"
    ]
    destinationDir = sourceSets.generated.java.srcDirs.iterator().next()
}
----




## Project Structure
Front와 API 서버를 아예 프로젝트를 분리할 것인가?


## Source Structure


일단 J2EE 환경을 구성한다.  gradle을 이용하며 기본적인 메이븐 폴더 구조를 따른다.

----
Project
    src
        main
            java
            resources
            front
            generated
            webapp
        test
            java
            resources
----

## Packaging

src/main/webapp 의 성격이 애매해지게 되는데 소스 폴더이자 빌드 도구에 의해 생성되는 generated 폴더이기도 하게 된다.
변경되는 파일과 그렇지 않은 것을 분리해야 할지 말지에 대한  판단은 아직 노하우가 쌓이지 않아 뒤로 돌리고 여기에서는 하나의 폴더만 사용하기로 하였다.

또다른 고려 사항은 webapp에 package.json등 UI 개발에 관련된 설정이나 소스 파일을  webapp에 둘지 아니면 아예 src/main/front나 src/main/ui 등의 별도 폴더를 가져 갈지 인데, 분리해두고 web app 폴더를 output  폴더로 사용하면 나중에 배포를 위해 패키징할때 좀더 단순해 지니느 장점이 있다. 반면, 소스 폴더가 너무 많이 분리 되는 거 같은 의문과,  빌드 가 필요하지 않은 간단 한 JS 개발도 모두 분리해야 하는 고민이 또 생긴다.  일단은 분리해서 진행해 보기로 한다.



배포 구조를 고민할때 고려 해야 하는 것은 단일 어플리케이션 배포냐 아니면 어플리케이션과 정적 파일을 분리해서 배포 할것인가 이다.
여태까지 경험한 대부분의 SI 프로젝트에서는 정적파일은 Apache Docroot에 배포 하고, 어플리케이션은 J2EE WAS Doc root에 배포하는 방식으로 해왔다. 하지만 개발자 PC에서 개발할때는 하나처럼 동작할수 있는게 필요하기도 하다. 여기에 대한 좋은 아이디어는 아직 없다. 그래서 단일 폴더 webapp에 모두 넣고, 패키징을 나눠서 하는 방식으로 여태까지는 해왔는데 좀더 개선할 사항이 있을지 고민이 필요하다.

 - 문제: 제네레이션 된 파일들을 삭제 하고 싶을때 구분할 방법이 없다. src/main/frontGenerated 로 분리하기로 함
 - 2016-02-11 16:02:23 이클립스에서 두개의 폴더를 동시에 context root 로 할수 없다. 즉 Layered 구조를 만들어 낼수 없다.  더 고민해봐야 할듯



## Java build ##

자바 빌드는 당연히 gradle을 사용한다. 손에 익은 것이기도 하고.


## UI Build ##
Web pack Only? 아니면 gulp + web pack?


### Webpack ###
Hot Module Replace가 지속적으로 임시파일을 만들어 낸다.
이 파일을 생성하지 않게 하면 생산성이 떨어지고, 만들게 하면 src 폴더가 지저분해진다. 이것도 고민이 필요할듯

## UI Framework ##

Bootstrap? 아님 SmartAdmin?



### Bootstrap + React ###
React는 기본적으로  메인 컨텐츠에 해당하는 div 를 지정하여 innerHtml을 변경하는 방식으로 동작한다.
그런데 Bootstrap은 body 태그 밑에 nav 태그등을 이용하는데 css class가 적용되지 않는 문제가 있다.
이런 문제를 어떻게 해결할지 고민을 조금 해봐야 겠다.
class를 className으로 변경하니 해결 되었다.

html 조각으로 보이지만, js 코드인만큼 className을 사용해야 하는 듯
https://facebook.github.io/react/docs/jsx-in-depth.html 에서 class와 for는 사용할수 없다고 한다. class는 className으로 for는 htmlFor로 변경 해야 한다고 한다.

### React Router를 사용함. ###
browserHisotry 지원 여부에 따라 해시 기반 URL일지 일반 URL일지 정할수 있음.
단 모든 요청에 대해 index.html을 반환해야 하는데 여기에 대한 정책이 필요함




### URL 체계 ###
예쁘게가 우선이라면 /issues/123 이렇게 되겠지만 이 것은 default servlet을 교체해야 하며 모든 요청에 대해 index.html을 반환하면서도 정적 컨텐츠와 API 서버, 그리고 3rd 파티 JSP 등을 어떻게 넣을 것인가 등을 고려해 URL 체계를 잡이야함
이게 서블릿이 아니라면 큰 문제가 아니겠지만, 서블릿 체계에서는  request mapping  문자열 지원이 좀 이상하기 때문이다.

####  Servlet url-pattern ####
서블릿의  URL-Pattern 은 딱 3가지 형태만 지원하는데

  * Exact Pattern:  정확히 동일한 이름만 지원   ex: /folder/abc.html /folder/abc
  * Directory Pattern: 특정 디렉토리 이하  ex: /folder/abc/*
  * Extension Pattern:  특정 확장자 *.js, *.reports

url-pattern 에 의해 여러개의 서블릿이 매핑될수 있으면 배포가 실패해야 한다.
web.xml 에 선언된  url-pattern에 매핑되지 못한 요청은  default servlet("/") 에 의해 처리된다.

패턴들을 섞어서 사용하는게 않된다.   ( ex 디렉토리 + 확장자  /folder/*.js  이런게 되지 않는다).

그럼 여기서 헷갈리는 것 중에 하나가 "/"와 "/*"의 차이입니다.
"/"는 default servlet을 의미하는 것이기 때문에, url-pattern에 "/"을 사용하면, container내에 있는 default servlet을 override하게 됩니다. 다시 말해 "/"에 매핑된 servlet이 default servlet이 되는 것입니다. default servlet의 역할은 url-pattern에 매치되지 않는 주로 정적 리소스들을(js, css, html, png 등) 전송하는 것입니다.

"/*"은 모든 요청을 처리하겠다는 뜻입니다. "/*"에 매핑된 servlet은 서버의 모든 요청을 처리하게 되는데 js, css, png, html등을 servlet이 처리해 줘야 합니다. 때문에 별로 유용하지 않는 url pattern 입니다. 여기서 servlet path 는 빈문자열("")이 됩니다


###  URL을 어디에 매핑? ###
사용자가 브라우저에 /issues/123 를 호출하는 것은 "HTML" 을 요청할수 있다.
이 요청은 일반적인 웹이라면 그냥  HTML 을 생성해서 보내줄 것이다. 하지만  SPA 에서는 많이 달라진다.
아무 것도 없는 상태에서는  index.html 을 읽어 와서 내부  Router  에 의해  route  되어야 한다.
/app/issues/123  -> index.html

하지만 실제 데이터를 읽어 와야 하는 부분에서는  ajax 를 이용하게 될것이며, 이때는 실제  Service 를 호출한 결과를  JSON  형태로 반환해야 한다.
이 구분을 어떻게 할것인가가 결정이 필요한데

*  prefix  이용:
** /app/issues/123   -> Restful API

   장점: 테스트하기 쉽다.
   단점: 않예쁘다

   Serlvet Mapping 이 가능한가?:


*  Accept Header  이용:
** /issues/123 Accept html -> index.html
** /issues/123 Accept json -> 서비스 결과  JSON


버전 구분은 별도로 고려하기로 한다.

### SPA에서 index.html 매핑 ###

예전 버전의 브라우저는 history api를 지원하지 않기 때문에 hash anchor를 이용해 URL을 변경했다. 단점이기도 하지만 장점도 있는데 바로 모든 요청이 자동적으로 index.html로 간다는 것이다.

----
  /#goods/123 -> /index.html#goods/123
----

하지만 현대적인 브라우저라면 모두 history api를 지원하며 이를 이용한 URL이 추천된다.

 /goods/123 -> 이 요청에 대해 index.html을 반환할 필요가 있다.

그렇다면 모든 application/html 요청에 대해 index.html을 타게 끔 ServletFilter 를 추가할수 있다. AJAX 요청만 Controller로 가게 할수 있는 것이다.
하지만 그럴때 또 다른 문제가 발생하는데 단순 팝업 HTML등도 index.html을 통해서만 보이게 된다는 점이다. .html인 경우는 그냥 통과하게 할수 있지만, 그렇게 되면 다음과 같은 문제점이 발생할수 있다.

* URL 체계가 복잡해진다. 어떤 팝업은 SPA기반 URL(/notice/123), 어떤 팝업은 HTML기반 URL(/html/notice123.html)
* SPA가 언제나 단 하나의 Entry point를 가지게 제약이 발생한다는 점(index.html말고 event.html, promotion.html 등을 사용하고 싶을때 유연하게 확장하기가 어려움)
** 현재 어플리케이션은 단일 Entry point 를 가지지만, 규모가 더 커지거나 하나의 서버에서 여러 어플을 제공해야 하는등 복수 entry point에 대한 요구사항은 존재한다.

이 논의는 flat & simple한 URL 체계를 유지하면서 복수의 Entry point를 J2EE환경에서 어떻게 유연하게 제공할수 있느냐 라고 하는 문제로 귀결 된다.
(또는 엔터프라이즈 어플리케이션에서 flat & simple한 URL을 추구하는것이 맞느냐 라는 고민이 있다 )




#### 정적 컨텐츠 ####
----
/res/css/common.css -> static contents
----


### Front-end 보안 체계 ###
SPA어플 보안의 문제점은 모든 메커니즘이 결국 공개 된다는 것이다. JS 파일들을 분석하면 그만이기 때문이다.  if ( user.roles.contains('admin')) 이 붙어 있으면 어드민 권한이 필요한 기능이라는게 보이게 되기 때문이다. ServerSide Render일때는 그냥 렌더링에서 빼면 된는데 SPA는 그게 않된다.
이 문제를 해결하기가 쉽지는 않은데 설계적으로 권한에 대한 판정을 서버에만 위치 시키는게 그렇게 쉽지는 않기 때문인데,  격리시킬 방법을 고민해 봐야 겠다

간단히 생각하면, 모든 데이터에 대한 요청을 서버에서 권한을 체크해서 보내주면 될거 같다.
하지만 그렇게하면 간단한 기능에 대해서도 api를 만들어야 한다.



## CSRF ##

## Double Submit ##
과거 GUI 어플리케이션의 문제는 무언가 동작중에 다른것을 클릭하는등 복수의 이벤트가 동시에 진행되는 것을 관리하는 것이였다. 이것은 매우 복잡하고 어려운 일이였다.  그래서 Modal 모드나 위자드 창등 이벤트를 독점하는 방법을  많이 사용하였다.
비슷하게 SPA로 만들게 되면 버튼을 여러번 클릭하는 문제가 발생한다. 이를 해소하는 방법이 필요하다.  일단 아이디어만 적어 보기로 한다.

* Modal 이용
Transpanent Layer, Modal Layer Progress Bar등 여러 수단을 통해 화면 클릭 자체를 막는다
** 장점
*** AJAX처리 부분을 통해 공통화 시키기 쉽다

** 단점
*** 오류 처리 문제로 Modal을 해제 하지 못하면 어플리케이션 전체가 먹통이 된다
*** 각 기능별로 공통화에서 배제 하고 싶을때가 있다.

* 버튼 활성화/비활성화
전송 버튼만 활성화/비활성화 한다.

** 장점
*** 구현이 단순하다

** 단점
*** 기능 구현중 누락 가능성이 있다.
*** 화면에 여러개의 전송버튼이 있을때 모두 제어해야 한다


이 문제는 Client에서만 막을수 있는 문제는 아니므로 Server Side의 Double Submit을 막을 방법이 필요하다.

보통 많이 사용하는 편집페이지에 들어갈때 세션에 토큰을 발행하고, 저장 URL에서 토큰을 소비하는 방식인 Submit synchronization Token는 여기서 사용할수 없다.
편집페이지에 들어가도 서버에 요청이 오는게  없기 때문이다.

편집용 토큰을 발행하는 API를 제공하여 이를 이용하는 것도 방법일듯. 그런데 이건 좀 너무 오버 엔지니어링 같기도 하고..

Request Throatling에 기반하여 같은 URL에 대한 사간당 POST 요청을 제한하는 방식이 제일 무난해 보이긴하는데.... 해킹이나 공격 방어용으로도 적절해 보이고.. 이 방식은 Sticky session이 필요하고, POST 요청 이력을 저장할 메모리를 소비하는 점을 고려 해야 할듯





## Replay Attack ##




## Full SPA(Single Page Application) or Separated SPA or 일반 JSP 사이트? ##

일단 Full SPA로 하기로 함. 기술적 난이도가 제일 높을것이기 때문에 발생할수 있는 이슈를 대충 경험할수 있을듯.





## API Server ##





## GIT ##

git ignore: https://www.gitignore.io/api/eclipse%2Cgradle%2Cmaven%2Cosx%2Csvn%2Cintellij%2Cnode%2Cjava








## Application ##

### 감사 정보 ###
누가, 언제, 무엇을 이란 정보는 감사를 위해 기본적인 정보인데.. 이번 프로젝트에서는 필요없지만...


